### ISSUE TITLE
npm doesn't fetch last version of winston-amqp

### ISSUE THREAD

**Issue by antoinegomez** [kr1sp1n/winston-amqp#4]
I found out the file lib/amqp.js on my project does not include modifications of Issue #2 . Strange because I use the commit reference to my fork in the package.json, will investigate on my side because it can only be related to my fork.

https://github.com/TaDaweb/winston-amqp/blob/4a70e1171fa562db5886c9838080b9b2c94a8cf4/lib/winston-amqp.js

And my line in package.json:

<pre>
"winston-amqp": "git://github.com/TaDaweb/winston-amqp.git#4a70e1171fa562db5886c9838080b9b2c94a8cf4"
</pre>

So it can be a npm install error on my side.

The point of this issue is just to let you know that the version has not been updated since the patch on Issue #2 and when I browse the code on github using the tag/branch menu I don't see the patch. I don't know how npm exactly behave with tags etc. but it can be an issue for others too I don't know. 

Just a warning :)  

For the record, error throwned:

<pre>
Error: Unmatched field {"name":"exchange","domain":"shortstr"}
    at serializeFields (/opt/my_server/node_modules/winston-amqp/node_modules/amqp/amqp.js:781:17)
    at Connection._sendMethod (/opt/my_server/node_modules/winston-amqp/node_modules/amqp/amqp.js:1236:3)
    at Exchange._onMethod (/opt/my_server/node_modules/winston-amqp/node_modules/amqp/amqp.js:2096:25)
    at Exchange.Channel._onChannelMethod (/opt/my_server/node_modules/winston-amqp/node_modules/amqp/amqp.js:1572:14)
    at Connection._onMethod (/opt/my_server/node_modules/winston-amqp/node_modules/amqp/amqp.js:1103:28)
    at AMQPParser.self.addListener.parser.onMethod (/opt/my_server/node_modules/winston-amqp/node_modules/amqp/amqp.js:910:12)
    at AMQPParser._parseMethodFrame (/opt/my_server/node_modules/winston-amqp/node_modules/amqp/amqp.js:458:10)
    at frameEnd (/opt/my_server/node_modules/winston-amqp/node_modules/amqp/amqp.js:194:16)
    at frame (/opt/my_server/node_modules/winston-amqp/node_modules/amqp/amqp.js:179:14)
    at AMQPParser.header [as parse] (/opt/my_server/node_modules/winston-amqp/node_modules/amqp/amqp.js:165:14)
</pre>

Here is the config:

``` javascript
ar amqpTransport = new (AMQP)({
      silent: config.logger.silent || false
    , exchange: {
      name: config.logger.name,
      properties: {
        type: 'fanout',
        durable: true,
        autoDelete: false
      }
    }
    , host             : config.rabbit.host
    , port             : config.rabbit.port
    , vhost            : config.rabbit.vhost
    , login            : config.rabbit.login
    , password         : config.rabbit.password
    , transformMessage : transformMessage
    , handleExceptions : true
  });
```

Versions of modules found in package.json files : 

amqp: 0.1.6
winston: 0.7.2
winston-amq: 0.0.2

**Comment by kr1sp1n** [comment]
Thank you @antoinegomez for that important issue. It seems that I just forget to tag the master branch and to publish that to the npm registry. It's fixed now!
